"""Does Qualcomm's precompiled Whisper actually run on the Snapdragon NPU, and how fast?

Why this is separate from bench_arm.py
--------------------------------------
bench_arm.py measures Whisper through onnxruntime-genai, which owns the whole pipeline: mel
extraction, the decode loop, the tokenizer. Asking it to use the NPU produced a clean negative -
every model fell back to the CPU and got slightly slower, because HTP needs static shapes and
quantised weights and those models are float with a KV cache that grows a step at a time.

Qualcomm publishes models that do not have that problem. They are genuinely NPU-shaped:

  encoder   input_features [1, 80, 3000] uint16  ->  24 cross-attention caches, uint8
  decoder   input_ids [1, 1] int32, attention_mask [1, 1, 1, 200] uint16,
            24 self caches in [12, 1, 64, 199] uint8, 24 cross caches from the encoder
            ->  logits [1, 51865, 1, 1] uint16, 24 self caches out

Fixed shapes throughout, w8a16 quantisation, and the KV cache lifted out of the graph into a
fixed 199-slot buffer the caller rolls by hand. That is exactly the surgery HTP requires, and it
is why these can run on the NPU when an off-the-shelf export cannot.

What this measures, and what it does not
----------------------------------------
It measures whether the graphs load on QNN and how long the encoder pass and a decoder step
take. It does NOT transcribe: the inputs are synthetic. That is deliberate and it is sound for
timing, because every shape here is static, so the work per step does not depend on the values.

There is no CPU comparison to be had from these files, and that turns out to be the useful part.
The .onnx is a wrapper holding a single EPContext node; the CPU provider refuses it outright
with "EPContext node generated by 'QNN' is not compatible with any execution provider added to
the session". So unlike the earlier float experiment, where QNN quietly handed everything back
to the CPU and looked like a measurement, **if these load at all they are running on the NPU**.
A number here cannot be a fallback in disguise.

The baseline to judge them against is therefore the CPU figures from bench_arm.py on the same
laptop: whisper-base at about 300 ms, whisper-small at about 1000 ms, against a 1000 ms budget.

Real transcription needs a mel front end, quantisation with the scales embedded in the wrapper,
greedy sampling over dequantised logits, and a tokenizer - a Whisper implementation rather than a
benchmark. Worth writing only if the numbers below justify it, which is the question.

Usage
-----
On a Snapdragon X, with ARM64 Python 3.12:

    curl -L -o bench_qnn_whisper.py https://raw.githubusercontent.com/desigrit/sunno/master/bench/bench_qnn_whisper.py
    py -3.12 bench_qnn_whisper.py --setup

--setup installs onnxruntime-qnn and fetches the model. Add --cpu to also time the same graphs
on the CPU provider, which is the comparison that matters.
"""

from __future__ import annotations

import argparse
import json
import platform
import sys
import time
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent

REQUIREMENTS = ["onnxruntime-qnn", "numpy"]

# Qualcomm AI Hub, model whisper_small_quantized, release v0.59.0. w8a16 - weights at 8 bits,
# activations at 16 - which is the precision their Snapdragon X build ships and the one HTP
# wants. The float builds of the same model exist but are the case already shown to fall back.
ASSETS = {
    "small-w8a16-x-elite": (
        "https://qaihub-public-assets.s3.us-west-2.amazonaws.com/qai-hub-models/models/"
        "whisper_small_quantized/releases/v0.59.0/"
        "whisper_small_quantized-precompiled_qnn_onnx-w8a16-qualcomm_snapdragon_x_elite.zip"
    ),
    "small-w8a16-x2-elite": (
        "https://qaihub-public-assets.s3.us-west-2.amazonaws.com/qai-hub-models/models/"
        "whisper_small_quantized/releases/v0.59.0/"
        "whisper_small_quantized-precompiled_qnn_onnx-w8a16-qualcomm_snapdragon_x2_elite.zip"
    ),
}

# A caption-length utterance. Whisper pads every window to 30 s so the encoder cost is fixed;
# what varies with speech length is how many decoder steps run, and this is a fair number for
# a conversational turn.
DECODE_STEPS = 24

_MACHINE_NAMES = {0x0000: "unknown", 0x014C: "x86", 0x8664: "x64", 0x01C4: "ARM32", 0xAA64: "ARM64"}


def machines() -> tuple[str, str]:
    """(process machine, native machine). See bench_arm.py for why not platform.machine()."""
    try:
        import ctypes
        from ctypes import wintypes

        k = ctypes.WinDLL("kernel32", use_last_error=True)
        k.GetCurrentProcess.restype = wintypes.HANDLE
        k.IsWow64Process2.argtypes = [wintypes.HANDLE, ctypes.POINTER(wintypes.USHORT),
                                      ctypes.POINTER(wintypes.USHORT)]
        k.IsWow64Process2.restype = wintypes.BOOL
        proc, nat = wintypes.USHORT(), wintypes.USHORT()
        if not k.IsWow64Process2(k.GetCurrentProcess(), ctypes.byref(proc), ctypes.byref(nat)):
            return "unknown", "unknown"
        nat_name = _MACHINE_NAMES.get(nat.value, f"0x{nat.value:04x}")
        if proc.value == 0:
            return nat_name, nat_name
        return _MACHINE_NAMES.get(proc.value, f"0x{proc.value:04x}"), nat_name
    except Exception:
        return "unknown", "unknown"


def bootstrap() -> int:
    """Install into a venv beside this script and re-run there."""
    import subprocess

    venv = ROOT / ".venv-qnn"
    python = venv / "Scripts" / "python.exe"
    if not python.is_file():
        print(f"  creating {venv}")
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)

    print(f"  installing {', '.join(REQUIREMENTS)}")
    subprocess.run([str(python), "-m", "pip", "install", "--quiet", "--upgrade", "pip"], check=False)
    result = subprocess.run([str(python), "-m", "pip", "install", "--quiet", *REQUIREMENTS])
    if result.returncode != 0:
        print("\n  Install failed. onnxruntime-qnn needs ARM64 Python 3.12 on Windows.")
        return result.returncode

    forwarded = [a for a in sys.argv[1:] if a != "--setup"]
    print(f"  re-running inside {python.name}\n")
    return subprocess.run([str(python), str(Path(__file__).resolve()), *forwarded]).returncode


def fetch_model(name: str, url: str, cache: Path) -> Path | None:
    """Download and unpack one Qualcomm asset, skipping work already done."""
    import urllib.request

    target = cache / name
    if (target / "metadata.json").is_file():
        return target
    for sub in target.glob("*/metadata.json"):
        return sub.parent

    cache.mkdir(parents=True, exist_ok=True)
    archive = cache / f"{name}.zip"
    if not archive.is_file():
        print(f"    downloading {name} (about 280 MB)")
        try:
            urllib.request.urlretrieve(url, archive)
        except Exception as exc:  # noqa: BLE001
            print(f"    download failed: {str(exc)[:160]}")
            return None

    print("    unpacking")
    try:
        with zipfile.ZipFile(archive) as z:
            z.extractall(target)
    except Exception as exc:  # noqa: BLE001
        print(f"    unpack failed: {str(exc)[:160]}")
        return None

    if (target / "metadata.json").is_file():
        return target
    for sub in target.glob("*/metadata.json"):
        return sub.parent
    print("    no metadata.json in the archive")
    return None


def make_session(path: Path, provider: str):
    """Open an EPContext ONNX on the requested provider.

    The .onnx here is a wrapper: a single EPContext node naming a .bin beside it that holds the
    graph already compiled for Hexagon. So this either loads on QNN or it does not - there is no
    partial-offload middle ground to misread.
    """
    import onnxruntime as ort

    options = ort.SessionOptions()
    options.log_severity_level = 3

    if provider == "qnn":
        import onnxruntime_qnn

        providers = [("QNNExecutionProvider", {"backend_path": onnxruntime_qnn.get_qnn_htp_path()})]
    else:
        providers = ["CPUExecutionProvider"]

    session = ort.InferenceSession(str(path), sess_options=options, providers=providers)
    return session, session.get_providers()


def synthetic_inputs(session, meta_inputs: dict, encoder_outputs: dict | None = None) -> dict:
    """Build correctly shaped inputs from the model's own declaration.

    Read off the session rather than hardcoded, so this keeps working when Qualcomm publishes a
    different size or revises the cache length. Values are zeros: shapes are static here, so the
    time per step does not depend on them, and zeros keep the run honest about the fact that
    nothing is being transcribed.
    """
    import numpy as np

    dtypes = {
        "tensor(uint16)": np.uint16, "tensor(uint8)": np.uint8,
        "tensor(int32)": np.int32, "tensor(int64)": np.int64,
        "tensor(float)": np.float32, "tensor(float16)": np.float16,
    }

    feed = {}
    for spec in session.get_inputs():
        if encoder_outputs and spec.name in encoder_outputs:
            feed[spec.name] = encoder_outputs[spec.name]
            continue
        dtype = dtypes.get(spec.type, np.float32)
        shape = [d if isinstance(d, int) and d > 0 else 1 for d in spec.shape]
        feed[spec.name] = np.zeros(shape, dtype=dtype)
    return feed


def measure(model_dir: Path, provider: str) -> dict:
    """Time an encoder pass and a run of decoder steps on one provider."""
    result: dict = {"provider": provider}

    encoder_path = model_dir / "encoder.onnx"
    decoder_path = model_dir / "decoder.onnx"
    if not encoder_path.is_file() or not decoder_path.is_file():
        return {"error": f"encoder.onnx/decoder.onnx not found in {model_dir}", **result}

    try:
        started = time.perf_counter()
        encoder, enc_providers = make_session(encoder_path, provider)
        decoder, dec_providers = make_session(decoder_path, provider)
        result["load_ms"] = round((time.perf_counter() - started) * 1000.0, 1)
        result["encoder_providers"] = enc_providers
        result["decoder_providers"] = dec_providers
    except Exception as exc:  # noqa: BLE001
        return {"error": f"load failed: {str(exc)[:220]}", **result}

    try:
        enc_feed = synthetic_inputs(encoder, {})
        best_enc = None
        enc_out = None
        for _ in range(3):
            started = time.perf_counter()
            outputs = encoder.run(None, enc_feed)
            elapsed = (time.perf_counter() - started) * 1000.0
            best_enc = elapsed if best_enc is None else min(best_enc, elapsed)
            enc_out = {o.name: v for o, v in zip(encoder.get_outputs(), outputs)}
        result["encoder_ms"] = round(best_enc, 1)
    except Exception as exc:  # noqa: BLE001
        return {"error": f"encoder failed: {str(exc)[:220]}", **result}

    try:
        # The encoder's cross caches feed the decoder unchanged for the whole utterance, which
        # is the point of splitting them: the expensive pass runs once per utterance and only
        # the small decoder step repeats.
        dec_feed = synthetic_inputs(decoder, {}, encoder_outputs=enc_out)
        best_step = None
        for _ in range(3):
            started = time.perf_counter()
            for _ in range(DECODE_STEPS):
                decoder.run(None, dec_feed)
            elapsed = (time.perf_counter() - started) * 1000.0
            best_step = elapsed if best_step is None else min(best_step, elapsed)
        result["decode_total_ms"] = round(best_step, 1)
        result["decode_step_ms"] = round(best_step / DECODE_STEPS, 2)
        result["utterance_ms"] = round(result["encoder_ms"] + best_step, 1)
        result["responsive"] = result["utterance_ms"] <= 1000
    except Exception as exc:  # noqa: BLE001
        return {"error": f"decoder failed: {str(exc)[:220]}", **result}

    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--setup", "-setup", action="store_true",
                        help="create a venv, install onnxruntime-qnn, and run inside it")
    parser.add_argument("--cpu", "-cpu", action="store_true",
                        help="also try the CPU provider; expected to fail, see the note below")
    parser.add_argument("--model", "-model", default="small-w8a16-x-elite",
                        choices=sorted(ASSETS), help="which Qualcomm asset to measure")
    parser.add_argument("--cache", "-cache", default=str(ROOT / ".qnn-models"),
                        help="where to keep downloaded models")
    parser.add_argument("--out", "-out", default=None, help="where to write the results")
    args = parser.parse_args()

    print("Sunno QNN Whisper probe")
    print("=" * 62)

    if args.setup:
        return bootstrap()

    process, native = machines()
    machine = {
        "python": platform.python_version(),
        "processor": platform.processor(),
        "process_machine": process,
        "native_machine": native,
        "emulated": process != native and "unknown" not in (process, native),
    }
    for key, value in machine.items():
        print(f"  {key:18} {value}")

    if machine["emulated"]:
        print("\n  STOP: this Python is emulated. Install the ARM64 build from python.org:")
        print("        https://www.python.org/ftp/python/3.12.10/python-3.12.10-arm64.exe")
        return 2

    try:
        import onnxruntime as ort
    except ImportError:
        print("\n  onnxruntime is not installed. Re-run with --setup")
        return 2

    print(f"  onnxruntime        {ort.__version__}")
    available = ort.get_available_providers()
    print(f"  providers          {', '.join(available)}")

    if "QNNExecutionProvider" not in available:
        if not args.cpu:
            print("\n  No QNN provider. onnxruntime-qnn is a separate package from plain")
            print("  onnxruntime; re-run with --setup to install it.")
            return 2
        # --cpu alone is still worth running: it exercises the whole harness and gives a
        # CPU number for these same graphs, which is the comparison the QNN result is judged
        # against. Useful on a machine with no NPU at all.
        print("\n  No QNN provider - measuring the CPU provider only.")

    print(f"\n  {args.model}")
    model_dir = fetch_model(args.model, ASSETS[args.model], Path(args.cache))
    if model_dir is None:
        return 1

    results: dict[str, dict] = {}
    providers_to_try = []
    if "QNNExecutionProvider" in available:
        providers_to_try.append("qnn")
    if args.cpu or not providers_to_try:
        providers_to_try.append("cpu")

    for provider in providers_to_try:
        measured = measure(model_dir, provider)
        results[provider] = measured
        if "error" in measured:
            print(f"    {provider:4} {measured['error']}")
            continue
        print(f"    {provider:4} load {measured['load_ms']:>9.1f} ms")
        print(f"         encoder      {measured['encoder_ms']:>8.1f} ms   (once per utterance)")
        print(f"         decode step  {measured['decode_step_ms']:>8.2f} ms   x{DECODE_STEPS}"
              f" = {measured['decode_total_ms']:.1f} ms")
        print(f"         utterance    {measured['utterance_ms']:>8.1f} ms   "
              f"{'responsive' if measured['responsive'] else 'over the 1000 ms budget'}")
        print(f"         ran on       {measured['encoder_providers']}")

    out = Path(args.out) if args.out else ROOT / f"qnn-whisper-{native}.json"
    out.write_text(json.dumps({"machine": machine, "model": args.model, "results": results},
                              indent=2), encoding="utf-8")
    print(f"\n  wrote {out}")
    print("\n  Note: this times the graphs, it does not transcribe. Timing is fair because every")
    print("  shape is static, but correctness is untested - that comes later if these numbers")
    print("  justify writing the mel front end and decode loop.")
    print("\n  Compare against bench_arm.py on this same laptop: whisper-base ~300 ms,")
    print("  whisper-small ~1000 ms on the CPU, against a 1000 ms budget.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
